### ISSUE TITLE
DOCTYPE lo tienes mal escrito

### ISSUE THREAD

**Issue by a19sotean** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-sergiovj2001-1#2]
DOCTYPE está mal escrito
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-sergiovj2001-1/blob/8ed3c389cd11709f6d57e3746cb37421baee437c/index.html#L1

**Comment by sergiovj2001** [comment]
vale perfecto,lo arreglo en un momento
