### ISSUE TITLE
Mal escrito

### ISSUE THREAD

**Issue by a19sotean** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-sergiovj2001-1#5]
Debería estar puesto así: <link rel="stylesheet" href="estilos.css">
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-sergiovj2001-1/blob/8ed3c389cd11709f6d57e3746cb37421baee437c/index.html#L8

**Comment by sergiovj2001** [comment]
no me has dicho como deberia estar

**Comment by a19sotean** [comment]
link rel="stylesheet" href="./css/style.css" entre los símbolos de menor que y mayor que
